project_identifier_env: CROWDIN_SITEMAKER_PROJECT_ID
api_key_env: CROWDIN_SITEMAKER_API_KEY
base_path: ./
preserve_hierarchy: true
files:
  -
    source: '/docs/docs/*.md'
    translation: '/docs/website/translated_docs/%two_letters_code%/%original_file_name%'
  -
    source: '/docs/website/i18n/en.json'
    translation: '/docs/website/i18n/%two_letters_code%.json'
  -
    source: '/docs/website/versioned_docs/**/*.md'
    translation: '/docs/website/translated_docs/%two_letters_code%/%original_file_name%'
  -
    source: '/language/**/*.php'
    translation: '/language/%two_letters_code%/%original_file_name%'
